name: autocomplete_google_places_widget
description: A wrapper around Flutter's default Autocomplete widget that leverages the Google Places API to provide real-time place suggestions as users type
version: 0.0.1
homepage:
repository: https://github.com/dhiaCodes/autocomplete_google_places_widget
issue_tracker: https://github.com/dhiaCodes/autocomplete_google_places_widget/issues
topics:
  - autocomplete
  - google places 



environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

